name: currency
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
 
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  random_string: ^2.3.1
  
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  flutter_admin_scaffold: ^1.3.0
  shared_preferences: ^2.3.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4

  cached_network_image: ^3.4.0
  firebase_storage: ^12.1.3
  file_picker: ^8.0.7
  http: ^1.2.2
  fl_chart: ^0.68.0
  firebase_messaging: ^15.0.4
  intl: ^0.19.0
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.0
  flutter_typeahead: ^4.0.0
  rflutter_alert: ^2.0.7
  liquid_swipe: ^3.1.0
  card_swiper: ^3.0.1

  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
 
flutter:
  assets:
    - assets/
    - assets/Logo/w.webp

  
 
  uses-material-design: true


